# this is the load balancer for the deploymeny app on port 8080
apiVersion: v1
kind: Service
metadata:
  name: solidproject-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080          # Expose the service on port 8080 to the outside 
      targetPort: 8080    # Maps to our container app port
  selector:
    app: myapp  # This should match the label in your Deployment
